modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "music_silencer"
version = "1.0.0"
displayName = "Music Silencer"
authors = "Riburitu"
description = "Silencia completamente la música de Minecraft en el cliente."

[[dependencies.music_silencer]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "CLIENT"
